### PR TITLE
Create readme

### PR DESCRIPTION
**Pull request by dougaitken**
Not 100% certain of the flow of the data but it's a start

### CODE REVIEW

**Comment by dougaitken** [comment]
Also, closes #1

**Comment by andrew** [comment]
Almost, when dasher finds a new pull request event, it posts it to the main 24pr which checks to see if the user that opened it is participating in 24pr. 

If they are, it records the pull request and posts that to the 24pr firewall.

**Comment by dougaitken** [comment]
Ah, so it validates it against the users, cool. 

24pr firewall, or firehose @andrew?

**Comment by andrew** [comment]
Firehose, sorry, autocorrect on my phone!

**Comment by dougaitken** [comment]
hahah just wanted to check, make sure I hadn't missed something.

:shipit:

**Comment by andrew** [comment]
Brilliant, thanks!

**Pull request merged**
